version: '3.8'

services: 
  portainer: 
    image: portainer/portainer-ce:2.11.1
    ports: 
      - 9443:9443
      - 9000:9000
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data 
      
volumes:
  portainer_data: 