version: '3.8'

services: 
  frontend: 
    build: ../../frontend
    ports:
      - 80:80

  backend:
    image: backend:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - "backend_db:/opt/db"
      - "backend_uploads:/opt/uploads"
      
volumes:
  backend_db:
    name: home_is_database_prod
  backend_uploads:
    name: home_is_uploads_prod