version: '3'

services: 
  database: 
    image: postgres:14
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_USER=pguser
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer: 
    image: adminer
    ports: 
      - 18080:8080

volumes: 
  pgdata: 