spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pguser
    username: pguser
    password: pgpassword
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml

storage:
  local:
    folder: ./storage

management:
  endpoints:
    web:
      cors:
        allowed-methods: GET
        allowed-origins: '*'
      exposure:
        include: info,health