spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pguser
    username: pguser
    password: pgpassword
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.${security.cognito.region}.amazonaws.com/${security.cognito.user-pool-id}
      client:
        provider:
          cognito:
            issuer-uri: https://cognito-idp.${security.cognito.region}.amazonaws.com/${security.cognito.user-pool-id}
            user-name-attribute: email
        registration:
          cognito:
            provider: cognito
            client-id: ${security.cognito.client-id}
            client-secret: ${security.cognito.client-secret}
            scope: openid
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml

storage:
  s3:
    region: ${aws-ssm:/dev/home-storage/s3/region}
    valid-seconds: 30
    bucket: ${aws-ssm:/dev/home-storage/s3/name}

security:
  cognito:
    user-pool-id: ${aws-ssm:/prod/home-storage/cognito/pool-id}
    region: ${aws-ssm:/prod/home-storage/cognito/region}
    client-id: ${aws-ssm:/prod/home-storage/cognito/client-id}
    client-secret: ${aws-ssm:/prod/home-storage/cognito/client-secret}
    target-user-group: ${aws-ssm:/prod/home-storage/cognito/target-group}

management:
  endpoints:
    web:
      cors:
        allowed-methods: GET
        allowed-origins: '*'
      exposure:
        include: info,health
logging:
  level:
    org:
      springframework:
        security: DEBUG