spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pguser
    username: pguser
    password: pgpassword
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml

storage:
  s3:
    region: ${aws-ssm:/dev/home-storage/s3/region}
    valid-seconds: 30
    bucket: ${aws-ssm:/dev/home-storage/s3/name}

management:
  endpoints:
    web:
      cors:
        allowed-methods: GET
        allowed-origins: '*'
      exposure:
        include: info,health