spring:
  datasource:
    url: jdbc:postgresql://${aws-ssm:/prod/home-storage/rds/host}:${aws-ssm:/prod/home-storage/rds/port}/${aws-ssm:/prod/home-storage/rds/name}
    username: ${aws-ssm:/prod/home-storage/rds/username}
    password: ${aws-ssm:/prod/home-storage/rds/password}

storage:
  local:
    folder: ./storage