spring:
  datasource:
    url: jdbc:h2:mem:storage_in_memory
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml

storage:
  local:
    folder: ./storage

management:
  endpoints:
    web:
      cors:
        allowed-methods: GET
        allowed-origins: '*'
      exposure:
        include: info,health