spring:
  datasource:
    url: jdbc:postgresql://${aws-ssm:/prod/home-storage/rds/host}:${aws-ssm:/prod/home-storage/rds/port}/${aws-ssm:/prod/home-storage/rds/name}
    username: ${aws-ssm:/prod/home-storage/rds/username}
    password: ${aws-ssm:/prod/home-storage/rds/password}

storage:
  s3:
    region: ${aws-ssm:/prod/home-storage/s3/region}
    bucket: ${aws-ssm:/prod/home-storage/s3/name}

security:
  cognito:
    user-pool-id: ${aws-ssm:/prod/home-storage/cognito/pool-id}
    region: ${aws-ssm:/prod/home-storage/cognito/region}
    client-id: ${aws-ssm:/prod/home-storage/cognito/client-id}
    client-secret: ${aws-ssm:/prod/home-storage/cognito/client-secret}
    target-user-group: ${aws-ssm:/prod/home-storage/cognito/target-group}