CREATE TABLE DEVICES (
                         DEVICE_ID IDENTITY PRIMARY KEY,
                         DEVICE_TITLE VARCHAR(255),
                         DEVICE_ALIAS VARCHAR(255),
                         DEVICE_FLAT_ID INT,
                         DEVICE_NEED_READINGS TINYINT DEFAULT 0,
                         DEVICE_NEED_INVOICES TINYINT DEFAULT 0,
                         DEVICE_NEED_RECEIPTS TINYINT DEFAULT 0
);

ALTER TABLE DEVICES ADD CONSTRAINT DEVICE_ALIAS_UNIQUE UNIQUE (DEVICE_ALIAS);
ALTER TABLE DEVICES ADD CONSTRAINT DEVICE_FLAT_FK FOREIGN KEY (DEVICE_FLAT_ID) REFERENCES FLATS (FLAT_ID);