CREATE TABLE DEVICE_READINGS (
    READING_ID IDENTITY PRIMARY KEY ,
    READING_DEVICE_ID INT,
    READING_FLAT_ID INT,
    READING_YEAR INT,
    READING_DATE DATE,
    READING_VALUE INT NULL,
    READING_INVOICE_FILE_ID INT NULL,
    READING_RECEIPT_FILE_ID INT NULL
);

ALTER TABLE DEVICE_READINGS ADD CONSTRAINT READING_DEVICE_FK FOREIGN KEY (READING_DEVICE_ID)
    REFERENCES DEVICES(DEVICE_ID);

ALTER TABLE DEVICE_READINGS ADD CONSTRAINT READING_FLAT_FK FOREIGN KEY (READING_FLAT_ID)
    REFERENCES FLATS(FLAT_ID);

ALTER TABLE DEVICE_READINGS ADD CONSTRAINT READING_INVOICE_FILE_FK FOREIGN KEY
    (READING_INVOICE_FILE_ID) REFERENCES FILES(FILE_ID);

ALTER TABLE DEVICE_READINGS ADD CONSTRAINT READING_RECEIPT_FILE_FK FOREIGN KEY
    (READING_RECEIPT_FILE_ID) REFERENCES FILES(FILE_ID);