version: '3'

services:
  mongo-storage: 
    image: mongo
    ports:
      - 27017:27017

  mongo-express: 
    image: mongo-express
    depends_on:
      - mongo-storage
    ports: 
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo-storage:27017/
