AWSTemplateFormatVersion: 2010-09-09
Description: Resources for the Home Storage application
Parameters: 
  StorageS3Prefix: 
    Type: String
    Description: Prefix used to create S3 buckets
    Default: abarmin-home-storage
  CognitoUserPoolName: 
    Type: String
    Description: Name of the user pool
    Default: abarmin-home-storage-user-pool
  CognitoLoginPageDomain: 
    Type: String
    Description: Domain name used to generate Cognito Login UI
    Default: abarmin-home-storage-auth
  CognitoLoginCallbackUrls: 
    Type: CommaDelimitedList
    Description: List of URLs allowed for auth redirects
    Default: http://localhost:8080/login/oauth2/code/cognito
  CognitoUserGroupName: 
    Type: String
    Description: Name of the user group which stores users with access to the application
    Default: abarmin-home-storage-users

Resources: 
  ################################################################################################
  ### S3 buckets
  ################################################################################################
  StorageS3Production:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties: 
      BucketName: !Join ["-", [ !Ref StorageS3Prefix, "production-2022" ]]

  StorageS3Development: 
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties: 
      BucketName: !Join ["-", [ !Ref StorageS3Prefix, "dev-2022" ]]

  ################################################################################################
  ### Amazon Cognito User pool
  ################################################################################################
  HomeInformationSystemUserPool:
    Type: AWS::Cognito::UserPool
    Properties: 
      AccountRecoverySetting: 
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 2
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: False
        UnusedAccountValidityDays: 7
      AutoVerifiedAttributes:
        - email
      MfaConfiguration: "OFF"
      UsernameAttributes: 
        - email
      UsernameConfiguration: 
        CaseSensitive: False
      UserPoolName: !Ref CognitoUserPoolName
      EmailConfiguration: 
        EmailSendingAccount: COGNITO_DEFAULT

  HomeInformationSystemUserPoolLoginPage: 
    Type: AWS::Cognito::UserPoolDomain
    Properties: 
      UserPoolId: !Ref HomeInformationSystemUserPool
      Domain: !Ref CognitoLoginPageDomain

  HomeInformationSystemUserPoolClient: 
    Type: AWS::Cognito::UserPoolClient
    Properties: 
      UserPoolId: !Ref HomeInformationSystemUserPool
      GenerateSecret: True
      ClientName: HomeInformationSystem
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthFlows: 
        - code
      CallbackURLs: !Ref CognitoLoginCallbackUrls
      SupportedIdentityProviders: 
        - COGNITO
      AllowedOAuthScopes: 
        - email
        - openid

  HomeInformationSystemUserPoolGroup: 
    Type: AWS::Cognito::UserPoolGroup
    Properties: 
      Description: Users who have access to the application
      GroupName: !Ref CognitoUserGroupName
      UserPoolId: !Ref HomeInformationSystemUserPool

  ################################################################################################
  ### AWS SSM Parameter Store parameters
  ################################################################################################
  ParameterStorageS3Production: 
    Type: AWS::SSM::Parameter
    Properties: 
      Name: /prod/home-storage/s3/name
      Description: Name of the production S3 bucket
      Tier: Standard
      Type: String
      Value: !Join ["-", [ !Ref StorageS3Prefix, "production-2022" ]]

  ParameterStorageS3Development: 
    Type: AWS::SSM::Parameter
    Properties: 
      Name: /dev/home-storage/s3/name
      Description: Name of the development S3 bucket
      Tier: Standard
      Type: String
      Value: !Join ["-", [ !Ref StorageS3Prefix, "dev-2022" ]]

  ParameterCognitoRegion:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: /prod/home-storage/cognito/region
      Description: Region in which Cognito User Pool is deployed
      Tier: Standard
      Type: String
      Value: !Ref "AWS::Region"

  ParameterCognitoUserPoolId: 
    Type: AWS::SSM::Parameter
    Properties: 
      Name: /prod/home-storage/cognito/pool-id
      Description: Cognito User Pool ID
      Tier: Standard
      Type: String
      Value: !Ref HomeInformationSystemUserPool

  ParameterCognitoInformationSystemClientId: 
    Type: AWS::SSM::Parameter
    Properties: 
      Name: /prod/home-storage/cognito/client-id
      Description: Cognito Client ID
      Tier: Standard
      Type: String
      Value: !Ref HomeInformationSystemUserPoolClient

  ParameterCognitoUserGroup:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: /prod/home-storage/cognito/target-group
      Description: Name of the group with users who have access to the app
      Tier: Standard
      Type: String
      Value: !Ref CognitoUserGroupName

  # This parameter is created by bash script
  # ParameterCognitoInformationSystemClientSecret: 
  #   Type: AWS::SSM::Parameter
  #   Properties: 
  #     Name: /prod/home-storage/cognito/client-secret
  #     Description: Cognito Client Secret
  #     Tier: Standard
  #     Type: String
  #     Value: !GetAtt HomeInformationSystemUserPoolClient.ClientSecret