GET http://localhost:8080/files/6243108b41180e58c4569272

###
POST http://localhost:8080/files
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="files.http"
Content-Type: text/plain

12345
----WebKitFormBoundary7MA4YWxkTrZu0gW