name: Build Backend

on:
  workflow_call:
    inputs:
      source_branch:
        description: Branch to build
        type: string
        required: true
      artifact_name: 
        description: Name of the artifact
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with: 
          ref: ${{ inputs.source_branch }}
      
      - name: Install Java 
        uses: actions/setup-java@v2
        with: 
          distribution: 'liberica'
          java-version: '17'

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v1
          
      - name: Build Spring Boot app
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          
          cd ./backend
          chmod +x ./mvnw
          ./mvnw clean package