name: Build Backend

on:
  workflow_call:
    inputs:
      source_branch:
        description: Branch to build
        type: string
        required: true
    outputs:
      artifact_name: 
        description: Name of the artifact

env:
  ARTIFACT_NAME: backend-${{ inputs.source_branch }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with: 
          ref: ${{ inputs.source_branch }}
      
      - name: Install NodeJS
        uses: actions/setup-node@v3.0.0
        with: 
          node-version: 17.x
          
      - name: Restore cache
        uses: actions/cache@v3.0.1
        with: 
          path: ./backend/node_modules
          key: backend-${{ hashFiles('./backend/package-lock.json') }}
          
      - name: Install dependencies
        run: |
          cd ./backend
          npm install
          
      - name: Build
        run: |
          cd ./backend
          npm run build  

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./backend