name: Build Backend

on:
  workflow_call:
    inputs:
      source_branch:
        description: Branch to build
        type: string
        required: true
      artifact_name: 
        description: Name of the artifact
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with: 
          ref: ${{ inputs.source_branch }}
      
      - name: Install Java 
        uses: actions/setup-java@v2
        with: 
          distribution: 'liberica'
          java-version: '17'
          
      - name: Build Spring Boot app
        run: |
          cd ./backend
          chmod +x ./mvnw
          ./mvnw clean package