name: Build Docker Image for backend

on: 
  workflow_call:
    inputs:
      source_branch:
        description: Branch to build
        type: string
        required: true
      docker_registry:
        description: Docker registry to login
        type: string
        required: true
      docker_username:
        description: User to login to Docker registry
        type: string
        required: true
      docker_password:
        description: Password to login to Docker registry
        type: string
        required: true
      image_tag: 
        description: Image tag to assign
        type: string
        required: true

jobs:
  build-image-backend: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with: 
          ref: ${{ inputs.source_branch }}

      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version ./backend/package.json -r'          
          
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.docker_registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with: 
          context: ./backend
          push: true
          tags: |
            ${{ inputs.image_tag }}
            backend-${{ steps.version.outputs.value }}