name: Build pull request

on:
  pull_request:

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install NodeJS
        uses: actions/setup-node@v3.0.0
        with: 
          node-version: 17.x
          
      - name: Restore cache
        uses: actions/cache@v3.0.1
        with: 
          path: ./frontent/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./frontend/package-lock.json') }}
          
      - name: Install dependencies
        run: |
          cd ./frontend
          npm install
          
      - name: Build
        run: |
          cd ./frontend
          npm run build

  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install NodeJS
        uses: actions/setup-node@v3.0.0
        with: 
          node-version: 17.x

      - name: Restore cache
        uses: actions/cache@v3.0.1
        with: 
          path: ./backend/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./backend/package-lock.json') }}          
          
      - name: Install dependencies
        run: |
          cd ./backend
          npm install
          
      - name: Build
        run: |
          cd ./backend
          npm run build
