name: Build pull request

on:
  pull_request:

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Build frontend
        uses: ./github/workflows/build-frontend
        with: 
          source_branch: ${{ env.GITHUB_REF }}

  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Build backend
        uses: ./github/workflows/build-backend
        with: 
          source_branch: ${{ env.GITHUB_REF }}
