name: Build mater branch

on: 
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-frontend:
    uses: ./.github/workflows/build-frontend.yml
    with: 
      source_branch: ${{ github.ref }}
      artifact_name: frontend-${{ github.sha }}
      artifact_upload: false

  build-backend:
    uses: ./.github/workflows/build-backend.yml
    with: 
      source_branch: ${{ github.ref }}
      artifact_name: backend-${{ github.sha }}
      artifact_upload: false

  build-image-backend:
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.ref }}

      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version ./backend/package.json -r'          
          
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build Docker image
        run: |
          cd ./backend
          IMAGE_ID_BASE=ghcr.io/${{ github.repository_owner }}/homeis-backend
          IMAGE_VERSION_SHA=${IMAGE_ID_BASE}:${{ github.sha }}
          IMAGE_VERSION_APP=${IMAGE_ID_BASE}:${{ steps.version.outputs.value }}

          docker build -t ${IMAGE_VERSION_SHA} -t ${IMAGE_VERSION_APP} .
          docker push ${IMAGE_VERSION_SHA}
