name: Build mater branch

on: 
  push:
    branches:
      - master

  workflow_dispatch:
    

jobs:
  build-frontend:
    uses: ./.github/workflows/build-frontend.yml
    with: 
      source_branch: ${{ github.ref }}
      artifact_name: frontend-${{ github.sha }}
      artifact_upload: false

  build-backend:
    uses: ./.github/workflows/build-backend.yml
    with: 
      source_branch: ${{ github.ref }}
      artifact_name: backend-${{ github.sha }}
      artifact_upload: false

  build-image-backend:
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.ref }}

      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version ./backend/package.json -r'          
          
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}          

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with: 
          context: ./backend
          push: true
          tags: |
            backend-${{ github.sha }}
            backend-${{ steps.version.outputs.value }}